### PR TITLE
Support for sensor information

### PR DESCRIPTION
**Pull request by bboehmke**
I added basic support to retrieve (and update) sensor information from a bridge.

I also tried to add a simple test for this feature.

### CODE REVIEW

**Comment by Collinux** [comment]
At a first glance the code looks good, thank you for taking the time to contribute this! 
I currently don't have a sensor in my hue system so I can't truly validate the code yet... I'll get a hold of one and check back on this. Feel free to ping me if it slips my mind.

**Comment by bboehmke** [comment]
I renamed the function to refresh.

Btw the daylight sensor is provided by the bridge itself so at least one sensor shuold be present in each bridge.

**Comment by mitchellrj** [comment]
Hi, I tested this PR on my own setup and added a few extra bits in #16.

**Comment by Collinux** [comment]
I just ordered a sensor so I can test this PR and @mitchellrj 's PR.

**Pull request merged**
